// Auto-configures the LAN dev host for WSL phone/device testing.
//
// On every `pnpm dev` this detects the Windows host's current LAN IPv4 and
// writes .env.development.local with nip.io-based URLs, so a phone on the same
// network can reach the WSL dev server. Next.js env precedence
// (.env.development.local > .env.local) means these override the committed
// localhost defaults, and a new DHCP lease is picked up automatically — no
// hand-editing env or next.config.
//
// Detection uses PowerShell, which works in both WSL NAT and mirrored
// networking modes (it reads the Windows LAN adapter, not the 172.x WSL
// vEthernet). Set DEV_HOST_IP to override. If no IP is found (not WSL, or
// interop disabled), it leaves config untouched and dev falls back to
// whatever .env.local provides (localhost).

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = join(process.cwd(), '.env.development.local');

function detectHostIp() {
  if (process.env.DEV_HOST_IP) return process.env.DEV_HOST_IP.trim();
  // The active adapter that owns a default gateway is the real LAN NIC; the
  // WSL vEthernet adapter (172.x) has no gateway and is skipped.
  //
  // execFileSync (not execSync) so the PowerShell `$_`/`$null` are passed as a
  // literal argument — a shell would otherwise expand them before PowerShell
  // sees the query.
  const psScript =
    "(Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway -ne $null -and $_.NetAdapter.Status -eq 'Up' } | Select-Object -First 1).IPv4Address.IPAddress";
  try {
    const out = execFileSync('powershell.exe', ['-NoProfile', '-Command', psScript], {
      stdio: ['ignore', 'pipe', 'ignore'],
    }).toString();
    const ip = out.replace(/\r/g, '').trim().split(/\s+/)[0];
    if (/^\d{1,3}(\.\d{1,3}){3}$/.test(ip)) return ip;
  } catch {
    // interop off / not WSL — fall through
  }
  return null;
}

const ip = detectHostIp();
if (!ip) {
  console.warn(
    '[setup-dev-env] No Windows host LAN IP detected (not WSL, or interop off). ' +
      'Leaving .env.development.local untouched; dev uses .env.local (localhost).',
  );
  process.exit(0);
}

const host = `${ip}.nip.io`;
const base = `http://${host}:3000`;
const body = `# AUTO-GENERATED by scripts/setup-dev-env.mjs on each \`pnpm dev\`. DO NOT EDIT.
# Detected Windows host LAN IP: ${ip}
# Overrides the localhost defaults in .env.local (Next precedence:
# .env.development.local > .env.local) so a phone/device on the LAN can reach
# the WSL dev server via nip.io. Regenerated every run, so a new DHCP lease
# just works — no hand-editing env or next.config.
BETTER_AUTH_URL=${base}
APP_URL=${base}
COOKIE_DOMAIN=.${host}
TRUSTED_ORIGINS=${base},http://*.${host}:3000,http://localhost:3000,http://*.localhost:3000
DEV_ALLOWED_ORIGIN_HOST=${host}
`;

writeFileSync(OUT, body);
console.log(`[setup-dev-env] LAN dev host: ${base}  (club subdomains: http://<slug>.${host}:3000)`);
